<?php namespace JF;
/**

Copyright 2020 JQueryForm.com
License: http://www.jqueryform.com/license.php

FormID:  jqueryform-8bbd53
Date:    2020-10-17 16:39:41
Version: v3.0.3
Generated by http://www.jqueryform.com

PHP 5.3+ is required.
If mailgun is used AND the form has file upload field, PHP 5.5+ is required.

*/

class Config {
	private static $config;

    public static function getConfig( $decode = true ){
    	self::$config = self::_getConfig( $decode );
    	self::overwriteConfig();
    	return self::$config;
    }

    private static function _getConfig( $decode = true ){
        ob_start();
        // ---------------------------------------------------------------------
        // JSON format config
        // Note: please make a copy before you edit config manually
        // ---------------------------------------------------------------------

/**JSON_START**/ ?>
{
    "formId": "jqueryform-8bbd53",
    "email": {
        "to": "ivannav.mateusv@utadeo.edu.co",
        "cc": "",
        "bcc": "",
        "subject": "Formulario desde sitio web \"EL PORTILLO\"",
        "template": ""
    },
    "admin": {
        "users": "admin:64fe9",
        "dataDelivery": "emailOnly"
    },
    "thankyou": {
        "url": "",
        "message": "{f1} gracias por comunicarte con L\u00e1cteos \"El Portillo\", tu mensaje ser\u00e1 le\u00eddo y contestado en el menor tiempo posible.",
        "seconds": "15"
    },
    "autoResponse": {
        "includeAttachments": true,
        "subject": "Contacto L\u00e1cteos \"El Portillo\"",
        "template": "{f1} gracias por contactarnos, por favor no responda este mensaje, su respuesta se dar\u00e1 en las pr\u00f3ximas 24 hrs."
    },
    "seo": {
        "trackerId": "",
        "title": "",
        "description": "",
        "keywords": "",
        "author": ""
    },
    "mailer": "local",
    "smtp": {
        "host": "",
        "user": "",
        "password": ""
    },
    "mailgun": {
        "domain": "",
        "apiKey": "",
        "fromEmail": "",
        "fromName": ""
    },
    "styles": {
        "iCheck": {
            "enabled": true,
            "skin": "flat",
            "colorScheme": "blue"
        },
        "Select2": {
            "enabled": true
        }
    },
    "logics": [],
    "fields": [
        {
            "label": "Nombre",
            "field_type": "name",
            "field_options": {
                "size": "small",
                "sender": "fullname",
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "placeholder": "Nombre y Apellido ",
                "addon": {
                    "leftIcon": "glyphicon glyphicon-user"
                }
            },
            "id": "f1",
            "cid": "c1"
        },
        {
            "label": "Tel\u00e9fono",
            "field_type": "email",
            "field_options": {
                "size": "small",
                "sender": true,
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "email": {
                        "enabled": true
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "fa fa-phone",
                    "leftText": ""
                },
                "placeholder": "Celular o tel\u00e9fono de contacto"
            },
            "id": "f2",
            "cid": "c2"
        },
        {
            "label": "Correo",
            "field_type": "paragraph",
            "field_options": {
                "images": {
                    "urls": "",
                    "slideshow": false
                },
                "validators": {
                    "required": {
                        "enabled": true
                    }
                },
                "addon": {
                    "leftIcon": "fa fa-envelope"
                },
                "placeholder": "Correo electr\u00f3nico "
            },
            "id": "f3",
            "cid": "c3"
        },
        {
            "label": "\u00bfC\u00f3mo te podemos ayudar?",
            "field_type": "text",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "size": "small",
                "addon": {
                    "leftIcon": "fa fa-question-circle"
                },
                "placeholder": "Describe en pocas palabras como te podemos ayudar",
                "validators": {
                    "required": {
                        "enabled": true
                    },
                    "alphanumeric": {
                        "enabled": false
                    },
                    "min": {
                        "enabled": false
                    }
                }
            },
            "id": "f4",
            "cid": "c25"
        },
        {
            "label": "Selecciona la raz\u00f3n por la que nos escribes",
            "field_type": "radio",
            "required": true,
            "field_options": {
                "images": {
                    "urls": "",
                    "style": [],
                    "slideshow": false
                },
                "options": [
                    {
                        "label": "Petici\u00f3n",
                        "checked": true
                    },
                    {
                        "label": "Queja o reclamo",
                        "checked": false
                    },
                    {
                        "label": "Duda",
                        "checked": false
                    }
                ],
                "presetJson": "",
                "style": {
                    "columns": "col-1"
                },
                "validators": {
                    "min": {
                        "enabled": true
                    },
                    "max": {
                        "enabled": false,
                        "msg": ""
                    },
                    "required": {
                        "enabled": true
                    }
                },
                "hidden": false
            },
            "id": "f7",
            "cid": "c55",
            "labelHide": false
        },
        {
            "label": "Submit Button",
            "field_type": "submit",
            "required": true,
            "field_options": {
                "page": {
                    "title": "Submit",
                    "labelPrev": "< Back",
                    "showPageNumnber": false,
                    "pageNumberText": "{page} \/ {total}"
                },
                "images": {
                    "urls": "",
                    "slideshow": false
                }
            },
            "labelHide": true,
            "submit": {
                "label": "Enviar ",
                "icon": "fa fa-send-o",
                "checkRequiredFields": ""
            },
            "id": "f0",
            "cid": "c0"
        }
    ],
    "gdpr": {
        "consentFieldId": "",
        "saveData": "always"
    },
    "licenseKey": "",
    "lang": {
        "language": "es"
    }
}
<?php /**JSON_END**/

        $json = ob_get_clean() ;

        return $decode ? json_decode( trim($json), true ) : $json;
    } // end of getConfig()

    private static function getValue( $fieldId, $default = NULL ){
        return isset( $_POST[$fieldId] ) ? $_POST[$fieldId] : $default ;
    }

    private static function overwriteConfig(){
    	//self::get_to();
    }

    private static function get_to(){
    	$value = self::getValue( 'c25' );
    	$to = array(
    		'Option 1' => 'a@a.com',
    		'Option 2' => 'b@b.com',
    		'Option 3' => 'c@c.com',
    	);

    	if( isset( $to[$value] ) ){
    		self::$config['email']['to'] = $to[ $value ];
    	};
    }

} // end of Config class